# Generated by Django 4.1.7 on 2023-03-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_order_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'Order_Items'},
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
