# Generated by Django 4.1.7 on 2023-03-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orderitems_order_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='order_items', to='shop.product'),
        ),
    ]
