# Generated by Django 4.1.7 on 2023-03-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orderitems_order_alter_orderitems_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_price',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item_amount',
            field=models.FloatField(default='0.00'),
        ),
    ]
