# Generated by Django 4.1.7 on 2023-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitems_item_price_orderitems_item_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item_qty',
            field=models.IntegerField(default='0'),
        ),
    ]
